#!/bin/bash -e
srcdir="$(dirname $(readlink -f $0))"
nroot="$srcdir/root"
disk="$(readlink -f "$1")"
dest="/mnt"
drive="${disk%%[0-9]}"

mount "$disk" "$dest"

[[ "$nroot" == "$dest" ]] && exit 1

cd "$srcdir"

./mount -v

cd "$nroot"

cp -a . "$dest"

cd "$srcdir"

./mount -v -u

mkdir -p "$dest/home/"

cp -a config "$dest/home/"

cp "$srcdir/post_instl" "$dest"

bdroot "$desk" "/post_instl" "$disk"
