#!/bin/bash -e
srcdir="$(dirname $(readlink -f $0))"
nroot="$srcdir/root"
disk="$(readlink -f "$1")"
dest="/mnt"
drive="${disk%%[0-9]}"

[[ "$nroot" == "$dest" ]] && {
    echo "Error: source and destination are the same."
    exit 1
}

echo "mounting destination..."
mount "$disk" "$dest"

echo "mounting source..."
cd "$srcdir"
./mount -v

echo "installing..."
cd "$nroot"
cp -au . "$dest"

echo "unmounting source..."
cd "$srcdir"
./mount -v -u

echo "copying config files..."
mkdir -p "$dest/home/"
cp -a config "$dest/home/"

echo "post_install..."
cp "$srcdir/post_instl" "$dest"
bdroot "$dest" "/post_instl" "$drive"
