#!/bin/bash
srcdir="$(dirname $(readlink -f $0))"
cd "$srcdir"
nroot="$srcdir/root"

_toslash() {
    echo $1 | tr _ /
}

mount_all() {
    mkdir -p "$nroot"
    opt=""
    [[ $no_ro == 1 ]] || opt="-r"
    mount $opt "$srcdir/root.img" "$nroot"

    while read file ;do
	mkdir -p "$srcdir/$file"
    done < "$srcdir/empty.lst"

    mount_lst=(frac/*)
    [[ -z $no_vfs ]] && mount_lst=("${mount_lst[@]}" vfs/*)

    for dir in "${mount_lst[@]}" ;do
	ndir="root/$(_toslash ${dir##*/})"
	mkdir -p "$ndir"
	mount --bind "$dir" "$ndir"
    done

    [[ -z $no_vfs ]] || return 0;
    for dir in $(cat tmpfs) ;do
	ndir="root/$dir"
	mkdir -p "$ndir"
	mount -t tmpfs -o nodev,nosuid,mode=1777 none "$ndir"
    done
}

umount_all() {
    [[ -z $no_vfs ]] && for dir in $(cat tmpfs) ;do
	ndir="root/$dir"
	umount "$ndir"
    done

    mount_lst=(frac/*)
    [[ -z $no_vfs ]] && mount_lst=("${mount_lst[@]}" vfs/*)

    for ((i = ${#mount_lst[@]} - 1;i >= 0;i--)) ;do
	ndir="root/$(_toslash ${mount_lst[i]##*/})"
	umount "$ndir"
    done
    umount "$nroot"
}

cmd=mount_all
unset no_vfs

for arg in "$@" ;do
    case "$arg" in
	-u)
	    cmd=umount_all
	    ;;
	-v)
	    no_vfs=1
	    ;;
        -w)
            no_ro=1
            ;;
	*)
	    echo "unrecognized arguement $arg" >&2
	    exit 1
	    ;;
    esac
done

$cmd
